version: "3.7"
services:
  app:
    build:
      args:
        user: test
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: main
    container_name: main-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - main

  npm:
    tty: true
    image: node:latest
    container_name: npm
    volumes:
      - ./:/var/www
    working_dir: /var/www/
    entrypoint: ['npm']
    networks:
      - main

  db:
    image: mysql:5.7
    container_name: main-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - .docker/data/mysql:/var/lib/mysql
    networks:
      - main

  nginx:
    image: nginx:alpine
    container_name: main-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - main

networks:
  main:
    driver: bridge
